In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10,5)

In [2]:
import json
import requests
import subprocess
import glob

In [3]:
process_chunksize = 10000
os.chdir('/Users/hudsonfinchbatista/Desktop/Python Datasets/Capstone')

mainCSV1 = 'CrimeChunk1.csv'
mainCSV2 = 'CrimeChunk2.csv'
mainCSV3 = 'CrimeChunk3.csv'
mainCSV4 = 'CrimeChunk4.csv'
mainCSV5 = 'CrimeChunk5.csv'
mainCSV6 = 'CrimeChunk6.csv'
mainCSV7 = 'CrimeChunk7.csv'
mainCSV8 = 'CrimeChunk8.csv'
mainCSV9 = 'CrimeChunk9.csv'
mainCSV10 = 'CrimeChunk10.csv'
mainCSV11 = 'CrimeChunk11.csv'
mainCSV12 = 'CrimeChunk12.csv'

mainDF1 = pd.read_csv(mainCSV1, chunksize=process_chunksize)
mainDF2 = pd.read_csv(mainCSV2, chunksize=process_chunksize)
mainDF3 = pd.read_csv(mainCSV3, chunksize=process_chunksize)
mainDF4 = pd.read_csv(mainCSV4, chunksize=process_chunksize)
mainDF5 = pd.read_csv(mainCSV5, chunksize=process_chunksize)
mainDF6 = pd.read_csv(mainCSV6, chunksize=process_chunksize)
mainDF7 = pd.read_csv(mainCSV7, chunksize=process_chunksize)
mainDF8 = pd.read_csv(mainCSV8, chunksize=process_chunksize)
mainDF9 = pd.read_csv(mainCSV9, chunksize=process_chunksize)
mainDF10 = pd.read_csv(mainCSV10, chunksize=process_chunksize)
mainDF11 = pd.read_csv(mainCSV11, chunksize=process_chunksize)
mainDF12 = pd.read_csv(mainCSV12, chunksize=process_chunksize)

In [4]:
census_api_url='https://api.census.gov/data/2019/acs/acs5?key=d62e9dc3485b7ad18ea2f4ebf8a2ebd6a41fd469&get=NAME,B01001_001E,B01002_001E,B19013_001E,B08301_001E,B08301_010E,B15003_001E,B15003_017E,B15003_022E,B23025_003E,B23025_005E&for=block%20group:*&in=state:24&in=county:031&in=tract:*'

responseCensus = requests.get(census_api_url, headers={'Content-Type': 'application/json'})
textCensus=json.loads(responseCensus.content)
tractDF = pd.DataFrame(textCensus)
print('Shape of census tract file: ' + str(tractDF.shape))

tractDF.rename(columns = tractDF.iloc[0], inplace=True)
tractDF = tractDF.iloc[1:]
tractDF.rename(index=str,columns={'B01001_001E':'Pop','B19013_001E':'Income',
                                  'B08301_001E':'Means of Transportation',
                                  'B08301_010E':'Public Transportation',
                                  'B15003_001E':'Educational Attainment','B15003_017E':'High School',
                                  'B15003_022E':'Bachelors',
                                  'B01002_001E':'Age','B23025_003E':'Total Laborforce',
                                  'B23025_005E':'Total Unemployed',
                                  'block group':'Block',
                                  'tract':'Tract'}, inplace=True)

Shape of census tract file: (615, 15)

In [31]:
tractDF.head()

,NAME,Pop,Age,Income,Means of Transportation,Public Transportation,Educational Attainment,High School,Bachelors,Total Laborforce,Total Unemployed,state,county,Tract,Block
1,"Block Group 4, Census Tract 7032.08, Montgomer...",1646,37.2,149375,822,92,1122,88,292,858,44,24,031,703208,4
2,"Block Group 4, Census Tract 7015.09, Montgomer...",3041,33.1,41104,1196,293,1778,412,242,1610,354,24,031,701509,4
3,"Block Group 2, Census Tract 7015.08, Montgomer...",590,31.3,62448,286,17,374,9,67,333,9,24,031,701508,2
4,"Block Group 1, Census Tract 7039.01, Montgomer...",1553,42.0,139318,928,157,1049,97,381,977,32,24,031,703901,1
5,"Block Group 2, Census Tract 7057.02, Montgomer...",1697,58.5,144688,719,43,1329,43,354,749,30,24,031,705702,2

In [6]:
tract2 = tractDF.sort_values(by='Tract')
tract2.head()

,Block,Tract,Pop,Income,Means of Transportation,Public Transportation,Educational Attainment,High School,Bachelors,Total Laborforce,Total Unemployed,Age
97,1,700101,1922,156250,1030,51,1314,110,355,1067,31,46.6
158,3,700101,800,135313,424,3,573,45,159,466,42,47.9
159,2,700101,1931,222619,942,62,1326,213,416,1105,54,48.7
494,3,700103,3112,172986,1733,169,2258,216,783,1768,35,48.1
176,2,700103,1017,218173,722,12,715,60,309,727,12,50.4

In [8]:
tractDF['Tract'][0]

703208

In [5]:
tractDF['Block'] = tractDF['Block'].apply(str)
tractDF['Tract'] = tractDF['Tract'].apply(str)

for i in range(0,len(tractDF)):
    tractDF['Block'][i] = tractDF['Tract'][i] + tractDF['Block'][i]
    
tractDF.head()

,NAME,Pop,Age,Income,Means of Transportation,Public Transportation,Educational Attainment,High School,Bachelors,Total Laborforce,Total Unemployed,state,county,Tract,Block
1,"Block Group 4, Census Tract 7032.08, Montgomer...",1646,37.2,149375,822,92,1122,88,292,858,44,24,031,703208,7032084
2,"Block Group 4, Census Tract 7015.09, Montgomer...",3041,33.1,41104,1196,293,1778,412,242,1610,354,24,031,701509,7015094
3,"Block Group 2, Census Tract 7015.08, Montgomer...",590,31.3,62448,286,17,374,9,67,333,9,24,031,701508,7015082
4,"Block Group 1, Census Tract 7039.01, Montgomer...",1553,42.0,139318,928,157,1049,97,381,977,32,24,031,703901,7039011
5,"Block Group 2, Census Tract 7057.02, Montgomer...",1697,58.5,144688,719,43,1329,43,354,749,30,24,031,705702,7057022

In [6]:
tractDF.set_index('Block', inplace=True)
tractDF.drop(['NAME', 'state', 'county','Tract'],inplace=True, axis=1)
tractDF=tractDF[['Pop','Income','Means of Transportation','Public Transportation','Educational Attainment','High School','Bachelors','Total Laborforce','Total Unemployed','Age']].apply(pd.to_numeric, errors='coerce')
print(tractDF.info())
print(tractDF.head(8))

<class 'pandas.core.frame.DataFrame'>
Index: 614 entries, 7032084 to 7013061
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Pop                      614 non-null    int64
 1   Income                   614 non-null    int64
 2   Means of Transportation  614 non-null    int64
 3   Public Transportation    614 non-null    int64
 4   Educational Attainment   614 non-null    int64
 5   High School              614 non-null    int64
 6   Bachelors                614 non-null    int64
 7   Total Laborforce         614 non-null    int64
 8   Total Unemployed         614 non-null    int64
 9   Age                      614 non-null    float64
dtypes: float64(1), int64(9)
memory usage: 52.8+ KB
None
          Pop  Income  Means of Transportation  Public Transportation  \
Block
7032084  1646  149375                      822                     92
7015094  3041   41104                     1196                    293
7015082   590   62448                      286                     17
7039011  1553  139318                      928                    157
7057022  1697  144688                      719                     43
7058003  1141  231250                      589                     27
7059032  1331  250001                      693                     34
7014143  2336   77457                     1222                    176

         Educational Attainment  High School  Bachelors  Total Laborforce  \
Block
7032084                    1122           88        292               858
7015094                    1778          412        242              1610
7015082                     374            9         67               333
7039011                    1049           97        381               977
7057022                    1329           43        354               749
7058003                     789           49        213               579
7059032                    1028           42        285               706
7014143                    1455          299        276              1358

         Total Unemployed   Age
Block
7032084                44  37.2
7015094               354  33.1
7015082                 9  31.3
7039011                32  42.0
7057022                30  58.5
7058003                 3  44.7
7059032                13  52.6
7014143                63  40.2

In [7]:
tractDF.head()

,Pop,Income,Means of Transportation,Public Transportation,Educational Attainment,High School,Bachelors,Total Laborforce,Total Unemployed,Age
Block,,,,,,,,,,
7032084,1646,149375,822,92,1122,88,292,858,44,37.2
7015094,3041,41104,1196,293,1778,412,242,1610,354,33.1
7015082,590,62448,286,17,374,9,67,333,9,31.3
7039011,1553,139318,928,157,1049,97,381,977,32,42.0
7057022,1697,144688,719,43,1329,43,354,749,30,58.5

In [8]:
for column in tractDF.columns:
    print(column)

Pop
Income
Means of Transportation
Public Transportation
Educational Attainment
High School
Bachelors
Total Laborforce
Total Unemployed
Age

In [7]:
#Define tract finding function
def getBlock(lonlat):
    block = -999
    api_url='https://geo.fcc.gov/api/census/area?lat='+str(lonlat[0])+'&lon='+str(lonlat[1])+'&format=json'
    headers = {'Content-Type': 'application/json'}
    response = requests.get(api_url, headers=headers)
    try:
        block=json.loads(response.content.decode('utf-8'))['results'][0]['block_fips'][5:12]
    except:
        print('No Block found from FCC geo API')
    return block

In [37]:
df1 = pd.DataFrame()
len(df1)

0

In [10]:
    df1 = pd.DataFrame()
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF1:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
            print(df_group.head(5))
    
            df1 = df1.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
   Unnamed: 0  Incident ID  Offence Code  CR Number    Dispatch Date / Time  \
0         742    201284536          1399  200015419  04/08/2020 03:24:11 PM
1         863    201283685          2610  200014367  03/29/2020 07:32:27 AM
2        1507    201260657          3562  190049016                     NaN
3        1850    201281812          2501  200012514  03/13/2020 11:51:37 PM
4        1929    201259611          2304  190047828  10/05/2019 01:36:00 PM

  NIBRS Code  Victims             Crime Name1  \
0        13B        2    Crime Against Person
1        26F        1  Crime Against Property
2        35A        1   Crime Against Society
3        250        1  Crime Against Property
4        23G        1  Crime Against Property

                                   Crime Name2                  Crime Name3  \
0                               Simple Assault         ASSAULT - 2ND DEGREE
1                               Identity Theft               IDENTITY THEFT
2                     Drug/Narcotic Violations  DRUGS - MARIJUANA - POSSESS
3                       Counterfeiting/Forgery            FORGERY OF CHECKS
4  Theft of Motor Vehicle Parts or Accessories         LARCENY - AUTO PARTS

   ... Pop Income Means of Transportation Public Transportation  \
0  ... NaN    NaN                     NaN                   NaN
1  ... NaN    NaN                     NaN                   NaN
2  ... NaN    NaN                     NaN                   NaN
3  ... NaN    NaN                     NaN                   NaN
4  ... NaN    NaN                     NaN                   NaN

   Educational Attainment High School Bachelors Total Laborforce  \
0                     NaN         NaN       NaN              NaN
1                     NaN         NaN       NaN              NaN
2                     NaN         NaN       NaN              NaN
3                     NaN         NaN       NaN              NaN
4                     NaN         NaN       NaN              NaN

  Total Unemployed  Age
0              NaN  NaN
1              NaN  NaN
2              NaN  NaN
3              NaN  NaN
4              NaN  NaN

[5 rows x 42 columns]
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
   Unnamed: 0  Incident ID  Offence Code  CR Number    Dispatch Date / Time  \
0       10011    201091844          3561   16038203                     NaN
1       11439    201276474          2305  200005846  02/04/2020 06:13:05 PM
2       11828    201307912          5404  200043097  11/01/2020 02:21:52 PM
3       11947    201294112          9201  200026672  07/09/2020 03:31:48 PM
4       12907    201261604          5311  190050255  10/19/2019 08:42:28 PM

  NIBRS Code  Victims             Crime Name1                  Crime Name2  \
0        35A        1   Crime Against Society     Drug/Narcotic Violations
1        23F        1  Crime Against Property     Theft From Motor Vehicle
2        90D        1   Crime Against Society  Driving Under the Influence
3        90Z        1                   Other           All Other Offenses
4        90C        1   Crime Against Society           Disorderly Conduct

                          Crime Name3  ... Pop Income Means of Transportation  \
0         DRUGS - MARIJUANA - SMUGGLE  ... NaN    NaN                     NaN
1                 LARCENY - FROM AUTO  ... NaN    NaN                     NaN
2  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
3                            OVERDOSE  ... NaN    NaN                     NaN
4   PUBLIC PEACE - DISORDERLY CONDUCT  ... NaN    NaN                     NaN

  Public Transportation  Educational Attainment High School Bachelors  \
0                   NaN                     NaN         NaN       NaN
1                   NaN                     NaN         NaN       NaN
2                   NaN                     NaN         NaN       NaN
3                   NaN                     NaN         NaN       NaN
4                   NaN                     NaN         NaN       NaN

  Total Laborforce Total Unemployed  Age
0              NaN              NaN  NaN
1              NaN              NaN  NaN
2              NaN              NaN  NaN
3              NaN              NaN  NaN
4              NaN              NaN  NaN

[5 rows x 42 columns]

In [11]:
len(df1)

20000

In [25]:
df1.Block.value_counts()

7038001    663
7025001    518
7008262    411
7025004    392
7007132    303
          ...
7032192      2
7002053      2
7008101      1
0010011      1
0015001      1
Name: Block, Length: 621, dtype: int64

In [12]:
df1.tail(20)

,Address Number,Age,Agency,Bachelors,Beat,Block,Block Address,CR Number,City,Crime Name1,...,State,Street Name,Street Prefix,Street Suffix,Street Type,Total Laborforce,Total Unemployed,Unnamed: 0,Victims,Zip Code
9980,10400.0,59.7,MCPD,216.0,2E3,7060123,10400 BLK AUTO PARK AVE,190053313,BETHESDA,Crime Against Property,...,MD,AUTO PARK,NaN,NaN,AVE,468.0,31.0,18108,1,20817.0
9981,7100.0,59.7,MCPD,216.0,2E3,7060123,7100 BLK WESTLAKE TER,200003855,BETHESDA,Crime Against Property,...,MD,WESTLAKE,NaN,NaN,TER,468.0,31.0,18180,1,20817.0
9982,10200.0,59.7,MCPD,216.0,2E3,7060123,10200 BLK WESTLAKE DR,190061967,BETHESDA,Crime Against Property,...,MD,WESTLAKE,NaN,NaN,DR,468.0,31.0,18440,1,20817.0
9983,7100.0,59.7,MCPD,216.0,2E3,7060123,7100 BLK WESTLAKE TER,190056881,BETHESDA,Crime Against Property,...,MD,WESTLAKE,NaN,NaN,TER,468.0,31.0,18817,1,20817.0
9984,8100.0,50.4,MCPD,314.0,2E4,7060131,8100 BLK SPLIT OAK DR,170523020,BETHESDA,Crime Against Property,...,MD,SPLIT OAK,NaN,NaN,DR,700.0,16.0,13025,1,20817.0
9985,9100.0,50.4,MCPD,314.0,2E4,7060131,9100 BLK SEVEN LOCKS RD,190055146,BETHESDA,Other,...,MD,SEVEN LOCKS,NaN,NaN,RD,700.0,16.0,16779,1,20817.0
9986,8300.0,50.4,MCPD,314.0,2E4,7060131,8300 BLK RIVER RD,200003797,BETHESDA,Crime Against Society,...,MD,RIVER,NaN,NaN,RD,700.0,16.0,17260,1,20817.0
9987,8800.0,50.4,MCPD,314.0,2E2,7060131,8800 BLK EARL CT,200003683,BETHESDA,Other,...,MD,EARL,NaN,NaN,CT,700.0,16.0,19639,1,20817.0
9988,7600.0,41.9,MCPD,367.0,2E2,7060132,7600 BLK DWIGHT DR,16040204,BETHESDA,Crime Against Property,...,MD,DWIGHT,NaN,NaN,DR,634.0,23.0,11533,1,20817.0
9989,7800.0,41.9,MCPD,367.0,2E3,7060132,7800 BLK DEMOCRACY BLV,190049862,BETHESDA,Other,...,MD,DEMOCRACY,NaN,NaN,BLV,634.0,23.0,12032,1,20817.0
9990,7600.0,41.9,MCPD,367.0,2E2,7060132,7600 BLK BRADLEY BLV,170507272,BETHESDA,Crime Against Society,...,MD,BRADLEY,NaN,NaN,BLV,634.0,23.0,13604,1,20817.0
9991,10000.0,41.9,MCPD,367.0,2E2,7060132,10000 BLK COVENTRY WAY,180007096,BETHESDA,Other,...,MD,COVENTRY,NaN,NaN,WAY,634.0,23.0,13844,1,20817.0
9992,10000.0,41.9,MCPD,367.0,2E2,7060132,10000 BLK WOODHILL RD,180042236,BETHESDA,Crime Against Property,...,MD,WOODHILL,NaN,NaN,RD,634.0,23.0,14655,1,20817.0
9993,9200.0,41.9,MCPD,367.0,2E2,7060132,9200 BLK ROSEHILL DR,16040602,BETHESDA,Crime Against Property,...,MD,ROSEHILL,NaN,NaN,DR,634.0,23.0,14808,1,20817.0
9994,9700.0,41.9,MCPD,367.0,2E2,7060132,9700 BLK GRENADIER CT,180055066,BETHESDA,Crime Against Property,...,MD,GRENADIER,NaN,NaN,CT,634.0,23.0,15090,1,20817.0
9995,7500.0,41.9,MCPD,367.0,2E2,7060132,7500 BLK GLENNON DR,190056208,BETHESDA,Crime Against Property,...,MD,GLENNON,NaN,NaN,DR,634.0,23.0,17166,1,20817.0
9996,9900.0,41.9,MCPD,367.0,2E2,7060132,9900 BLK SEVEN LOCKS RD,16041998,BETHESDA,Crime Against Property,...,MD,SEVEN LOCKS,NaN,NaN,RD,634.0,23.0,17836,1,20817.0
9997,8300.0,NaN,MCPD,NaN,3H1,8057001,8300 BLK TAHONA DR,16039194,SILVER SPRING,Crime Against Property,...,MD,TAHONA,NaN,NaN,DR,NaN,NaN,10153,1,20903.0
9998,8300.0,NaN,MCPD,NaN,3H1,8057001,8300 BLK TAHONA DR,16039771,SILVER SPRING,Crime Against Society,...,MD,TAHONA,NaN,NaN,DR,NaN,NaN,10802,1,20903.0
9999,8300.0,NaN,MCPD,NaN,3H1,8057001,8300 BLK TAHONA DR,16041226,SILVER SPRING,Crime Against Property,...,MD,TAHONA,NaN,NaN,DR,NaN,NaN,16707,1,20903.0

In [13]:
len(df1[~(df1['Block'] ==  -999)])

19949

In [14]:
df1['Age'].value_counts()

31.3    712
35.1    658
41.2    564
33.8    512
36.0    393
       ...
57.5      3
50.1      3
26.1      2
80.4      2
77.1      2
Name: Age, Length: 257, dtype: int64

In [23]:
for column in df1.columns:
    print(column)

Address Number
Age
Agency
Bachelors
Beat
Block
Block Address
CR Number
City
Crime Name1
Crime Name2
Crime Name3
Dispatch Date / Time
Educational Attainment
End_Date_Time
High School
Incident ID
Income
Latitude
Location
Longitude
Means of Transportation
NIBRS Code
Offence Code
PRA
Place
Police District Name
Police District Number
Pop
Public Transportation
Sector
Start_Date_Time
State
Street Name
Street Prefix
Street Suffix
Street Type
Total Laborforce
Total Unemployed
Tract
Unnamed: 0
Victims
Zip Code

In [25]:
df1.to_csv('MC_Crime1.csv')

In [8]:
df2 = pd.DataFrame();df3 = pd.DataFrame();df4 = pd.DataFrame();df5 = pd.DataFrame();
df6 = pd.DataFrame();df7 = pd.DataFrame();df8 = pd.DataFrame();df9 = pd.DataFrame();
df10 = pd.DataFrame();df11 = pd.DataFrame();df12 = pd.DataFrame()

In [10]:

    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF2:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df2 = df2.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [11]:
len(df2)

10000

In [12]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF3:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
            print(df_group.head(5))
    
            df3 = df3.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
   Unnamed: 0  Incident ID Offence Code  CR Number    Dispatch Date / Time  \
0       40536    201272175         2303  200000418  01/03/2020 01:27:20 PM
1       40603    201108686         5404   16059547                     NaN
2       40661    201108716         5404   16060195                     NaN
3       41255    201109146         5404   16060688                     NaN
4       41285    201109159         9199   16060674                     NaN

  NIBRS Code  Victims             Crime Name1                  Crime Name2  \
0        23C        1  Crime Against Property                  Shoplifting
1        90D        1   Crime Against Society  Driving Under the Influence
2        90D        1   Crime Against Society  Driving Under the Influence
3        90D        1   Crime Against Society  Driving Under the Influence
4        90Z        1                   Other           All Other Offenses

                          Crime Name3  ... Pop Income Means of Transportation  \
0               LARCENY - SHOPLIFTING  ... NaN    NaN                     NaN
1  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
2  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
3  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
4                  POLICE INFORMATION  ... NaN    NaN                     NaN

  Public Transportation  Educational Attainment High School Bachelors  \
0                   NaN                     NaN         NaN       NaN
1                   NaN                     NaN         NaN       NaN
2                   NaN                     NaN         NaN       NaN
3                   NaN                     NaN         NaN       NaN
4                   NaN                     NaN         NaN       NaN

  Total Laborforce Total Unemployed  Age
0              NaN              NaN  NaN
1              NaN              NaN  NaN
2              NaN              NaN  NaN
3              NaN              NaN  NaN
4              NaN              NaN  NaN

[5 rows x 42 columns]
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
   Unnamed: 0  Incident ID  Offence Code  CR Number    Dispatch Date / Time  \
0       50656    201277949          5404  200007778  02/16/2020 04:10:42 AM
1       51202    201115451          5404   17001252                     NaN
2       52008    201116106          3512   17001948                     NaN
3       52411    201116497          5404   17002545                     NaN
4       52999    201117020          2902   17002860                     NaN

  NIBRS Code  Victims             Crime Name1  \
0        90D        1   Crime Against Society
1        90D        1   Crime Against Society
2        35A        1   Crime Against Society
3        90D        1   Crime Against Society
4        290        1  Crime Against Property

                                Crime Name2  \
0               Driving Under the Influence
1               Driving Under the Influence
2                  Drug/Narcotic Violations
3               Driving Under the Influence
4  Destruction/Damage/Vandalism of Property

                          Crime Name3  ... Pop Income Means of Transportation  \
0  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
1  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
2            DRUGS - HEROIN - POSSESS  ... NaN    NaN                     NaN
3  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
4           DAMAGE PROPERTY - PRIVATE  ... NaN    NaN                     NaN

  Public Transportation  Educational Attainment High School Bachelors  \
0                   NaN                     NaN         NaN       NaN
1                   NaN                     NaN         NaN       NaN
2                   NaN                     NaN         NaN       NaN
3                   NaN                     NaN         NaN       NaN
4                   NaN                     NaN         NaN       NaN

  Total Laborforce Total Unemployed  Age
0              NaN              NaN  NaN
1              NaN              NaN  NaN
2              NaN              NaN  NaN
3              NaN              NaN  NaN
4              NaN              NaN  NaN

[5 rows x 42 columns]

In [13]:
len(df3)

20000

In [14]:
df3.to_csv('MC_Crime3.csv')

In [28]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF4:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
            print(df_group.head(5))
    
            df4 = df4.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
   Unnamed: 0  Incident ID  Offence Code  CR Number    Dispatch Date / Time  \
0       61466    201124422          3562   17012309                     NaN
1       63890    201126886          5404   17015387                     NaN
2       63993    201127116          2305   17015557                     NaN
3       63994    201127116          9099   17015557                     NaN
4       64730    201128661          5404  170500456  04/05/2017 01:35:39 AM

  NIBRS Code  Victims             Crime Name1                  Crime Name2  \
0        35A        1   Crime Against Society     Drug/Narcotic Violations
1        90D        1   Crime Against Society  Driving Under the Influence
2        23F        1  Crime Against Property     Theft From Motor Vehicle
3        90Z        1   Crime Against Society           All Other Offenses
4        90D        1   Crime Against Society  Driving Under the Influence

                          Crime Name3  ... Pop Income Means of Transportation  \
0         DRUGS - MARIJUANA - POSSESS  ... NaN    NaN                     NaN
1  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
2                 LARCENY - FROM AUTO  ... NaN    NaN                     NaN
3                  ALL OTHER OFFENSES  ... NaN    NaN                     NaN
4  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN

  Public Transportation  Educational Attainment High School Bachelors  \
0                   NaN                     NaN         NaN       NaN
1                   NaN                     NaN         NaN       NaN
2                   NaN                     NaN         NaN       NaN
3                   NaN                     NaN         NaN       NaN
4                   NaN                     NaN         NaN       NaN

  Total Laborforce Total Unemployed  Age
0              NaN              NaN  NaN
1              NaN              NaN  NaN
2              NaN              NaN  NaN
3              NaN              NaN  NaN
4              NaN              NaN  NaN

[5 rows x 42 columns]
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
   Unnamed: 0  Incident ID  Offence Code  CR Number    Dispatch Date / Time  \
0       70280    201149138          5404  170525620  08/18/2017 10:50:58 PM
1       70543    201149911          5404  170526934  08/26/2017 12:17:18 AM
2       71251    201152241          4199  170529265  09/07/2017 07:45:54 PM
3       71406    201152727          3562  170529932  09/11/2017 03:20:52 PM
4       71428    201152792          3562  170530656  09/14/2017 10:35:38 PM

  NIBRS Code  Victims            Crime Name1                  Crime Name2  \
0        90D        1  Crime Against Society  Driving Under the Influence
1        90D        1  Crime Against Society  Driving Under the Influence
2        90G        1  Crime Against Society        Liquor Law Violations
3        35A        1  Crime Against Society     Drug/Narcotic Violations
4        35A        1  Crime Against Society     Drug/Narcotic Violations

                          Crime Name3  ... Pop Income Means of Transportation  \
0  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
1  DRIVING UNDER THE INFLUENCE LIQUOR  ... NaN    NaN                     NaN
2           LIQUOR (DESCRIBE OFFENSE)  ... NaN    NaN                     NaN
3         DRUGS - MARIJUANA - POSSESS  ... NaN    NaN                     NaN
4         DRUGS - MARIJUANA - POSSESS  ... NaN    NaN                     NaN

  Public Transportation  Educational Attainment High School Bachelors  \
0                   NaN                     NaN         NaN       NaN
1                   NaN                     NaN         NaN       NaN
2                   NaN                     NaN         NaN       NaN
3                   NaN                     NaN         NaN       NaN
4                   NaN                     NaN         NaN       NaN

  Total Laborforce Total Unemployed  Age
0              NaN              NaN  NaN
1              NaN              NaN  NaN
2              NaN              NaN  NaN
3              NaN              NaN  NaN
4              NaN              NaN  NaN

[5 rows x 42 columns]

In [29]:
len(df4)

20000

In [15]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF5:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df5 = df5.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [16]:
len(df5)

20000

In [17]:
df5.to_csv('MC_Crime5.csv')

In [18]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF6:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df6 = df6.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [19]:
len(df6)

20000

In [20]:
df6.to_csv('MC_Crime6.csv')

In [21]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF7:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df7 = df7.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [22]:
len(df7)

20000

In [23]:
df7.to_csv('MC_Crime7.csv')

In [24]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF8:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df8 = df8.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [25]:
len(df8)

20000

In [26]:
df8.to_csv('MC_Crime8.csv')

In [27]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF9:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df9 = df9.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [28]:
len(df9)

20000

In [29]:
df9.to_csv('MC_Crime9.csv')

In [30]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF10:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df10 = df10.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [31]:
len(df10)

20000

In [32]:
df10.to_csv('MC_Crime10.csv')

In [33]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF11:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df11 = df11.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [34]:
len(df11)

20000

In [35]:
df11.to_csv('MC_Crime11.csv')

In [36]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF12:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df12 = df12.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(7000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [37]:
len(df12)

17000

In [38]:
df12.to_csv('MC_Crime12.csv')

In [10]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF2:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df2 = df2.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [11]:
len(df2)

10000

In [9]:
    itld=0
    itlu=1
    
    for mainDF_chunk in mainDF2:
            nLinesMainCSVd=itld*process_chunksize
            nLinesMainCSVu=itlu*process_chunksize
            print('New group from main DF, lines '+str(nLinesMainCSVd) + ' to ' + str(nLinesMainCSVu) )

            # Cleaning main
            mainDF_chunk.dropna(subset=['Location'],inplace=True)
            mainDF_chunk['Location']=mainDF_chunk['Location'].map(lambda x: eval(str(x)))
            mainDF_chunk[['Start_Date_Time','End_Date_Time']].apply(pd.to_datetime,errors='coerce')
            print('Dimension of main DF group:' + str(mainDF_chunk.shape))
    
            # Add Tract from FCC geo
            mainDF_chunk['Block']=mainDF_chunk.Location.map(lambda x: getBlock(x))
    
            df_group = pd.merge(mainDF_chunk,tractDF, how='left', on='Block', sort=True)
    
            df2 = df2.append(df_group,sort=True)
    
            itlu+=1
            itld+=1

New group from main DF, lines 0 to 10000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
New group from main DF, lines 10000 to 20000
Dimension of main DF group:(10000, 31)
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API
No Block found from FCC geo API

In [10]:
len(df2)

20000

In [11]:
df2.to_csv('MC_Crime2.csv')